version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001
      - NEXTAUTH_URL=http://127.0.0.1:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    network_mode: "host"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@127.0.0.1:5432/serverpanel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    network_mode: "host"
    privileged: true
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=serverpanel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: "host"
    restart: always

  nginx:
    image: nginx:alpine
    network_mode: "host"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${PANEL_SSL_KEY}:/etc/server-control-panel/ssl/private.key
      - ${PANEL_SSL_CERT}:/etc/server-control-panel/ssl/certificate.crt
    restart: always

volumes:
  postgres_data:

